### ISSUE TITLE
I cannot make it work

### ISSUE THREAD

**Issue by RenatoBello** [rajgoel/reveal.js-demos#1]
I tried to use this script (with some adjustments) and  also tried the script in this link: https://github.com/rajgoel/reveal.js-plugins/tree/master/customcontrols

But I am not able to make it work. Please, some help?
[test.html.zip](https://github.com/rajgoel/reveal.js-demos/files/2141711/test.html.zip)

Thanks

**Comment by rajgoel** [comment]
Does this show correctly for you: https://rajgoel.github.io/reveal.js-demos/customcontrols-demo.html#/ ?
